refugio/apps/adopcion/urls.py
from django.conf.urls import url
from apps.adopcion.views import inicio, SolicitudList

# para poder usarla ahi que importarla.

urlpatterns = [
    url(r'^$', inicio, name='inicio'),
    url(r'^solicitud/listar$', SolicitudList.as_view(), name='solicitud_listar'),

]

refugio/apps/mascota/urls.py
from django.conf.urls import url, include
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
    MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^lista$', MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eliminar'),





]

refugio/refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace='mascota')),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace='adopcion')),
    url(r'^mascota_crear/', include('apps.mascota.urls', namespace='mascota_crear')),
    url(r'^login')

]

refugio/apps/adopcion/models.py
from django.db import models


class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellidos)


class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True)
    numero_mascota = models.IntegerField()
    razones = models.TextField()

refugio/apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona


# Create your models here.

class Vacuna(models.Model):

    nombre = models.CharField(max_length=50)


class Mascota(models.Model):

    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

refugio/apps/seguridad/models.py
from django.db import models

# Create your models here.

refugio/apps/adopcion/forms.py
from django import forms

from apps.adopcion.models import Persona, Solicitud


class PersonaForm(forms.ModelForm):

    fields = [
        'nombre',
        'apellidos',
        'edad',
        'telefono',
        'email',
        'domicilio'
    ]

    labels = {
        'nombre': 'Nombre',
        'apellidos': 'Apellidos',
        'edad': 'Edad',
        'telefono': 'Telefono',
        'email': 'Email',
        'domicilio': 'Domicilio',
    }
    widgest = {
        'nombre':forms.TextInput(attrs={'class':'form-control'}),
        'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
        'edad': forms.TextInput(attrs={'class': 'form-control'}),
        'telefono': forms.TextInput(attrs={'class': 'form-control'}),
        'email': forms.TextInput(attrs={'class': 'form-control'}),
        'domicilio': forms.TextInput(attrs={'class': 'form-control'}),
    }


class SolicitudForm(forms.ModelForm):
    model = Solicitud
    fields = [
        'numeros_mascotas',
        'razones',
    ]
    labels = {
        'numeros_mascotas': 'Numeros_mascotas',
        'razones': 'Razones',
    }
    widgest = {
        'numeros_mascotas':forms.TextInput(attrs={'class':'form-control'}),
        'razones':forms.TextInput(attrs={'class':'form-control'}),

    }

refugio/apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota


class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]

        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aproximada': 'Edad_aproximada',
            'fecha_rescate': 'Fecha_rescate',
            'persona': 'Persona',
            'vacuna': 'Vacuna',
        }
        widgest = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'sexo': forms.TextInput(attrs={'class': 'form-control'}),
            'edad_aproximada': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_rescate': forms.TextInput(attrs={'class': 'form-control'}),
            'persona': forms.Select(attrs={'class': 'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
        }

refugio/apps/adopcion/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from apps.adopcion.models import Solicitud, Persona
from apps.adopcion.forms import SolicitudForm, PersonaForm
from django.core.urlresolvers import reverse_lazy



from django.http import HttpResponse


def inicio(request):
    return render(request, 'adopcion/inicio.html')


class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'


class SolicitudCreate(CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    succes_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data()

refugio/apps/mascota/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy


from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota


def index(request):
    return render(request, 'mascota/index.html')


def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    else:
        form = MascotaForm()
    return render(request, 'mascota/mascota_form.html', {'form': form})


def mascota_list(request):
    mascota = Mascota.objects.all().order_by('id')
    contexto = {'mascotas': mascota}
    return render(request, 'mascota/mascota_list.html', contexto)


def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_form.html', {'form': form})


def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_list')
    return render(request, 'mascota/mascota_delete.html', {'mascota': mascota})


class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'


class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    succes_url = reverse_lazy('mascota:mascota_listar')


class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    succes_url = reverse_lazy('mascota:mascota_listar')


class MascotaDelete(DeleteView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_delete.html'
    succes_url = reverse_lazy('mascota:mascota_listar')

refugio/templates/adopcion/adopcion_list.html
{% extends 'base/base.html' %}

refugio/templates/adopcion/inicio.html
{% extends 'base/base.html' %}

{% block content %}

<h4> este es el contenido de adopcion</h4>
{% endblock %}

refugio/templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

refugio/templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td>No. Solicitud </td>
            <td>Adoptante</td>
            <td>Razones</td>
            <td>Acciones</td>

        </tr>
    </thead>
    <tbody>
    {% if object_list %}
    {% for solicitud in object_list %}

        <tr>

            <td>{{ solicitud.id }}</td>
            <td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellidos }}</td>
            <td>{{ solicitud.numero_mascotas}</td>
            <td>{{ solicitud.razones }}</td>

            <td>
                <a class="btn btn-primary" href=""> Editar</a>
                <a class="btn btn-primary" href=""> ELIMINAR</a>
            </td>
        </tr>
    {% endfor %}
    {% else %}
    <h1> No hay ningun registro </h1>
    {% endif %}


    </tbody>
</table>

{% endblock %}

refugio/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
											<li><a href="{% url 'mascota:mascota_listar' %}">Lista</a></li>
											<li><a href="{% url 'mascota:mascota_crear' %}">Nueva Mascota</a></li>


				                        </ul>
		                      		</li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">

			                        	</ul>
			                        </li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="">Registro</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">

		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock %}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>

refugio/templates/base/header.html
<header>Hola</header>

refugio/templates/mascota/index.html
{% extends 'base/base.html' %}


{% block title%}
Mascota
{% endblock %}

{% block content %}
<h1>Contenido de la aplicación mascota</h1>
{% endblock %}

refugio/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
    <button class="btm btn-dager" type="submit">si, eliminar</button>
    <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
</form>
{% endblock %}

refugio/templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

refugio/templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td># </td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha rescate </td>
            <td>Adoptante </td>
        </tr>
    </thead>
    <tbody>
    {% if object_list %}
    {% for mascota in object_list %}

        <tr>
            <td>{{ mascota.id }}</td>
            <td>{{ mascota.nombre }}</td>
            <td>{{ mascota.edad_aproximada }}</td>
            <td> {{ mascota.fecha_rescate }}</td>
            <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}"> Editar</a>
                <a class="btn btn-primary" href="{% url 'mascota:mascota_eliminar' mascota.id %}"> ELIMINAR</a>
            </td>
        </tr>
    {% endfor %}
    {% else %}
    <h1> No hay ningun registro </h1>
    {% endif %}


    </tbody>
</table>

{% endblock %}